"""
Pharmacist Assistant Router
Approved users type a drug name and receive general, structured drug information
in Arabic, generated by Gemini (same key/failover as the rest of the app).
"""

from fastapi import APIRouter, Depends, HTTPException, status

from app.models.user import User
from app.schemas.assistant import DrugInfoRequest, DrugInfoResponse
from app.services.auth_service import get_current_approved_user
from app.services import assistant_service

router = APIRouter(prefix="/assistant", tags=["Assistant"])


@router.post("/drug-info", response_model=DrugInfoResponse)
async def drug_info(
    request: DrugInfoRequest,
    user: User = Depends(get_current_approved_user),
):
    """
    Return general drug information for the requested drug name.

    The user's own Gemini keys (AI settings) are preferred, falling back to the
    server keys. If the model doesn't recognise the drug, ``recognized`` is
    False and the client shows a clear "not recognised" message.
    """
    name = request.name.strip()
    if not name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Drug name is required.",
        )

    try:
        result = await assistant_service.get_drug_info(name, user)
    except assistant_service.AssistantServiceError as e:
        print(f"[Assistant Router] Lookup failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to fetch drug information. Please try again.",
        )

    return DrugInfoResponse(**result)
